### PR TITLE
fix(popover): focus outline

### LINKED ISSUE #38789: Unexpected focus outline (blue border) on Filter Badge popover
### Bug description
After page refresh, when hovering over the Filter Badge (indicator showing the count of applied filters) on a dashboard chart, a default blue focus outline appears around the popover container. This visual artifact is inconsistent with the rest of the Superset UI.

### How to reproduce the bug
1. Open a dashboard with filters and apply filters.
2. Refresh the page
3. Hover over the Filter Badge (the "1" or "2" icon next to the filter funnel).
4. Observe the blue border appearing around the "Applied filters" popover.

### Screenshots/recordings
[Paste your video or image here]

### Superset version
master / latest-dev

### Python version
3.9

### Node version
16

### Browser
Chrome

### Additional context
No response

### Checklist
- [x] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [x] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

### PR DESCRIPTION
**Pull request by miagood41**
### SUMMARY
Removes an unintended browser focus outline from the applied filters popover on dashboards.

The popover content can receive focus, which causes a default blue outline to appear after refreshing a dashboard and hovering over the applied filters badge. This change updates the filters details container and uses `:focus:not(:focus-visible)` so mouse hover does not show the outline while still allowing keyboard focus behavior.

### BEFORE/AFTER SCREENSHOTS OR ANIMATED GIF

No outline appears after refreshing the page with applied filters
no-outline-after-refresh

### TESTING INSTRUCTIONS

1. Open a dashboard 
2. Select and apply filters.
2. Refresh the dashboard page.
3. Select or Hover over the applied filters icon on a chart.
4. Confirm the applied filters popover appears without the blue focus outline.
5. Use keyboard navigation to focus the filter badge and confirm keyboard focus behavior is still visible.

### ADDITIONAL INFORMATION

- [x] Has associated issue: Fixes apache/superset#38789
- [ ] Required feature flags:
- [x] Changes UI
- [ ] Includes DB Migration (follow approval process in [SIP-59](https://github.com/apache/superset/issues/13351))
  - [ ] Migration is atomic, supports rollback & is backwards-compatible
  - [ ] Confirm DB migration upgrade and downgrade tested
  - [ ] Runtime estimates and downtime expectations provided
- [ ] Introduces new feature or API
- [ ] Removes existing feature or API

### CODE REVIEW

**Review by jsjlim27 — APPROVED** [review]
This fix is relevant to our core mission.

**Comment by Fikadulem** [comment]
@miagood41 Would you check and fix the failing checks? All checks should pass before you merge the PR.

File: superset-frontend/src/dashboard/components/FiltersBadge/Styles.tsx [hunk 1]
```diff
@@ -118,6 +118,10 @@ export const FiltersDetailsContainer = styled.div`
     overflow-x: hidden;
 
     color: ${theme.colorText};
+    
+    &:focus:not(:focus-visible) {
```
Comment (boredsenseless) [inline superset-frontend/src/dashboard/components/FiltersBadge/Styles.tsx:122]: The `&` parent selector is not supported in older browsers. Have you verified this change for all supported browsers/platforms?

Maybe @Fikadulem can help with verification?

**Review by boredsenseless — CHANGES_REQUESTED** [review]

File: superset-frontend/src/dashboard/components/FiltersBadge/Styles.tsx (hunk 1 above)
Comment (Fikadulem) [reply superset-frontend/src/dashboard/components/FiltersBadge/Styles.tsx:122]: @boredsenseless Sure, I will take look.

**Review by boredsenseless — APPROVED** [review]

**Review by Fikadulem — APPROVED** [review]
Looks good!
